version: "2"
services:
  web:
    # the application's web service (container) will use an image based on our Dockerfile
    build: "."
    # map the internal port 80 to port 8000 on the host
    ports:
      - "8000:80"
    # map the host directory to app (which allows us to see and edit files inside the container)
    volumes:
      - ".:/app:rw"
      - "./data:/data:rw"
    # the default command to run wheneve the container is launched
    command: python manage.py runserver 0.0.0.0:80
    # the URL 'postgres' will point to the application's db service
    links:
      - "db:postgres"
    env_file: .env-local
  db:
    # the application's web service will use an off-the-shelf image
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ".:/app:rw"
